---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app
  labels:
    app: capstone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: capstone
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 1
  template:
    metadata:
      labels:
        app: capstone
    spec:
      volumes:
      - name: uploads
        emptyDir: {}
      containers:
      - name: capstone
        image: coredns-c8589f55d-cklqr
        ports:
        - name: http
          containerPort: 80
        imagePullPolicy: "Always"
      nodeSelector:
        kubernetes.io/os: linux